version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432" # Mappt den PostgreSQL-Port 5432 auf deinen lokalen Port 5432
    environment:
      POSTGRES_USER: mtcg       # Setzt den PostgreSQL-Benutzer
      POSTGRES_PASSWORD: mtcg # Setzt das PostgreSQL-Passwort
      POSTGRES_DB: mctg_database       # Erstellt automatisch diese Datenbank
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistiert die Daten
    restart: always

volumes:
  postgres_data:
